name:                 paper-examples
version:              0.1.0.0
visibility:           public
id:                   paper-examples-0.1.0.0-inplace
key:                  paper-examples-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           egb2@cin.ufpe.br rsb6@cin.ufpe.br
author:               Enzo Bissoli & Rodrigo Santos
synopsis:             A mini subset of C in Parsec
category:             Language
abi:                  inplace
exposed:              True
exposed-modules:      CParser Symbol
import-dirs:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/dist-newstyle/build/x86_64-linux/ghc-9.12.2/paper-examples-0.1.0.0/build

library-dirs:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/dist-newstyle/build/x86_64-linux/ghc-9.12.2/paper-examples-0.1.0.0/build

library-dirs-static:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/dist-newstyle/build/x86_64-linux/ghc-9.12.2/paper-examples-0.1.0.0/build

dynamic-library-dirs:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/dist-newstyle/build/x86_64-linux/ghc-9.12.2/paper-examples-0.1.0.0/build

data-dir:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/.

hs-libraries:         HSpaper-examples-0.1.0.0-inplace
depends:              base-4.21.0.0-5b43 parsec-3.1.18.0-f2be
haddock-interfaces:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/dist-newstyle/build/x86_64-linux/ghc-9.12.2/paper-examples-0.1.0.0/doc/html/paper-examples/paper-examples.haddock

haddock-html:
    /var/home/egb2/git/IF688---Teoria-e-implementa-o-de-Linguagens-Computacioais/compiler-project-parser/paper-examples/dist-newstyle/build/x86_64-linux/ghc-9.12.2/paper-examples-0.1.0.0/doc/html/paper-examples
